---
title: "Using tidyr to wrangle data"
author: "Erica Bishop"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

library(tidyverse)
library(here)
library(janitor)
```

## Read in WB data files

```{r}
wb_indicators <- read_csv(here("data", "wb_indicators.csv"), na = c("..",""))

```

Now tidy up data

```{r}
#step one: get years into one column

#use single or double quotes around column names with numbers and spaces to make sure r knows what you're referring to

wb_indicators_long <- wb_indicators |> 
  pivot_longer(cols = `2001 [YR2001]`:`2020 [YR2020]`,
               names_to = "year",
               values_to = "indicator_value")

#note that year is a character class

```

Now use `separate()` to clean up the year column - split into year and year character

```{r}
#filter is for rows, select is for columns

wb_clean <- wb_indicators_long |> 
  separate(col = year, into = c("year", "year_chr"), sep = " ") |>
  select(-year_chr, -'Country Code', -'Series Code') |> 
  mutate(year = as.numeric(year)) |> 
  drop_na('Series Name') |> 
  pivot_wider(names_from = "Series Name", values_from = "indicator_value")

#Now the data is tidy!

#always look at the intermediate steps before deciding on your next step

#use pivot wider to widen variables trapped in 'Series Name' to be spread acorss multiple columns and get the values that populate the columns from indicator_value
#drop NA will drop an entire row with an NA value so BE CAREFUL!!

```

To see all of the unique values that exist in a series:
```{r}
unique(wb_clean$`Series Name`)
```

```{r}
#redname column headers so they aren't so unweildy
#with names(), be careful with order of things

names(wb_clean) <- c("country", "year", "access_clean_fuels_pp", "access_electricity_pp", "co2_emissions_kt", "fossil_fuel_cons_pct", "water_stress")

#can't pipe straight into names, that function is one that isn't built to accept a piped in argument

```

Now create a subset and plot (filter for rows)

```{r}

wb_subset <- wb_clean |> 
  filter(country %in% c("Canada", "China", "Tajikistan", "Norway"))

ggplot(data = wb_subset, aes(x = year, y = co2_emissions_kt)) +
  geom_line(aes(color = country)) +
  facet_wrap(~country)
  

```
For example, if we wanted to get rid of some of the country class variables that are larger region groupings, etc., then use:

```{r}
wb_example <- wb_subset |> 
  filter(!country %in% exclude_this)

#this gets rid of c
```











